### ISSUE TITLE
Notification: scheduled to be added to webui extension index if no objection is raised

### ISSUE THREAD

**Issue by w-e-w** [uwidev/sd_extension-prompt_formatter#10]
Hi @uwidev I'm one of the maintenance of [webui extension Index](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
we'd like to add your extension https://github.com/uwidev/sd_extension-prompt_formatter to the extension index
we would like to confirm with you before adding it
see https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/170

scheduled to be added after a week if we did not receive any negative response from you

**Comment by uwidev** [comment]
Yes, feel free to. Thank you for your contribution in making this possible!

**Comment by w-e-w** [comment]
merged
