### ISSUE TITLE
Feature request, support wildcards double underscore

### ISSUE THREAD

**Issue by tdtrumble** [uwidev/sd_extension-prompt_formatter#13]
Currently ext will remove double underscores used to indicate wildcards (https://github.com/adieyal/sd-dynamic-prompts.git)

**Comment by uwidev** [comment]
Fixed as of v0.4.2.

The current implementation is that if there's more than 1 consecutive underscore, it won't convert them to spaces. Probably not the best approach, since it won't fix excessive underscores on wildcards, but it'll work for now.
