### ISSUE TITLE
Does not preserve newlines

### ISSUE THREAD

**Issue by myplaceat9** [uwidev/sd_extension-prompt_formatter#15]
Thanks for the extension, I like it a lot.
An improvement I would like to see is an option to preserve newlines.
Newlines can make the prompt more readable, and in some cases are required when using other extensions, such as animatediff prompt travel or regional prompting.

**Comment by uwidev** [comment]
Should work now. 

Code is messy and needs quite a bit of refactoring for proper testing and development, but for new lines, it should be working.
