### ISSUE TITLE
Lora tags

### ISSUE THREAD

**Issue by Antivash** [uwidev/sd_extension-prompt_formatter#16]
Any chance to get an option to ignore the text inside of lora tags and just move it to the end without modifying it?  

The Bloodborne lora I am using has its alias as [XL]Bloodborne, so formatting swaps it from

`<lora:[XL]Bloodborne:1>`

to 

`<lora:(XL:0.91)Bloodborne:1>`

which fucks up generation:

`0: 640x576 1 person, 522.0ms
Speed: 11.0ms preprocess, 522.0ms inference, 13.8ms postprocess per image at shape (1, 3, 640, 576)
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001CC4D37AB60>, <modules.extra_networks.ExtraNetworkParams object at 0x000001CC4D378BE0>, <modules.extra_networks.ExtraNetworkParams object at 0x000001CC4D379F30>, <modules.extra_networks.ExtraNetworkParams object at 0x000001CC4D378220>]: ValueError
Traceback (most recent call last):
  File "J:\AIART\sdxl\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "J:\AIART\sdxl\extensions-builtin\Lora\extra_networks_lora.py", line 30, in activate
    te_multiplier = float(params.positional[1]) if len(params.positional) > 1 else 1.0
ValueError: could not convert string to float: '0.9524)Bloodborne'`

**Comment by uwidev** [comment]
Fixed in e2b86ecabb35109b40e8adb36e0e633e83f9d6f9
