### ISSUE TITLE
Request to Add License to project

### ISSUE THREAD

**Issue by WildBanjos** [uwidev/sd_extension-prompt_formatter#17]
I noticed that the extension currently doesn't have an license (open-source or otherwise), and I thought it might be a good idea to add one. Especially considering that the code is very well-commented and documented. Without one, people may be cautious about contributing or using your code to learn.

Please consider adding one, although it is in your right not to.

Thanks!

**Comment by uwidev** [comment]
https://github.com/uwidev/sd_extension-prompt_formatter/blob/main/LICENSE
