### ISSUE TITLE
Please add support for Gradio 4+ (new Forge versions)

### ISSUE THREAD

**Issue by alashakhanov** [uwidev/sd_extension-prompt_formatter#19]
ValueError: An event handler (format_prompt) didn't receive enough input values (needed: 8, got: 4).
Check if the event handler calls a Javascript function, and make sure its return value is correct.

**Comment by uwidev** [comment]
Could you elaborate on your workflow and interface? With the current commit of https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/aadc0f04c48eb19475752a4206420ea2004e2f42, which uses Gradio `4.40.0`, it functions fine on Txt2ing and Img2img workflows.

Are you using a custom workflow? Prompt formatter is **only** supposed to appear for the two workflows mentioned above.

Also, **even without the extension installed**, I get the following warning in my browser console:
```
Too many arguments provided for the endpoint.
```
Which is to say it might be an issue outside of this extension.

**Comment by alashakhanov** [comment]
> Could you elaborate on your workflow and interface? With the current commit of [lllyasviel/stable-diffusion-webui-forge@aadc0f0](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/aadc0f04c48eb19475752a4206420ea2004e2f42), which uses Gradio `4.40.0`, it functions fine on Txt2ing and Img2img workflows.
> 
> Are you using a custom workflow? Prompt formatter is **only** supposed to appear for the two workflows mentioned above, so it shouldn't be hooking into other workflows that have other inputs.
> 
> Also, **even without the extension installed**, I get the following warning in my browser console:
> 
> ```
> Too many arguments provided for the endpoint.
> ```
> 
> Which is to say it might be an issue outside of this extension.

I use main branch of the Forge. I tested this again without any other extensions installed. From the first startup everything works fine. Then, when you import a prompt from PNG Info (Sent to Txt2Img) and format the prompt, this error appears.

```
Traceback (most recent call last):
  File "D:\Program Files\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\Program Files\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Program Files\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1919, in process_api
    inputs = await self.preprocess_data(
  File "D:\Program Files\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1626, in preprocess_data
    self.validate_inputs(block_fn, inputs)
  File "D:\Program Files\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1608, in validate_inputs
    raise ValueError(
ValueError: An event handler (format_prompt) didn't receive enough input values (needed: 7, got: 4).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [<gradio.components.textbox.Textbox object at 0x000002942CAAB730>, <gradio.components.textbox.Textbox object at 0x000002942DD6D900>, <gradio.components.textbox.Textbox object at 0x000002942E3F1D50>, <gradio.components.textbox.Textbox object at 0x000002942E3F1060>, <gradio.components.textbox.Textbox object at 0x0000029430EBC040>, <gradio.components.textbox.Textbox object at 0x000002942F2AB490>, <gradio.components.textbox.Textbox object at 0x000002942F2ABA00>]
Received inputs:
    ["score_9, score_8_up, score_7_up, chun-li, brown hair, brown eyes, bangs, double bun, hair bun, blue bodysuit, stirrup stockings, sitting, solo", "text, bad anatomy", "", ""]
```

It also happens if you click the arrow button in a blue box to the right of the prompt format, it reuses the prompt from the last generation, even if there was none. I may reinstall it to verify again if no one can reproduce this.

**Comment by uwidev** [comment]
I have confirmed this error happens and am looking into it. It's late tonight so I'll get back to it tomorrow.

**Comment by uwidev** [comment]
So it seems like whenever you send an image from pnginfo Info to txt2img or img2img, it completely re-creates the UI instead of re-using the existing UI. Every single time you send from pnginfo, it increases the inputs by 2, one for positive and one for negative.

Should be able to fix this today, hopefully.
