### ISSUE TITLE
Do not convert square & curly braces to round ones.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [uwidev/sd_extension-prompt_formatter#2]
I really want to use this extension, but it incorrectly changes too many things that it shouldn't.

These: 
(the first line merges each of the words together, and the second line picks a word randomly for each image.)
```
[tall|blue|wide|red]
{tall|blue|wide|red}
```

are not the same as:

```
(tall|blue|wide|red:0.91)
(tall|blue|wide|redy:1.10)
```

Which is what the script converts them to.

**Comment by uwidev** [comment]
Currently being worked on.

**Comment by Oni4kage** [comment]
(extremely detailed CG unity 8k wallpaper), (full body angle:1.1), (detailed face:1.2) handsome, film photograph, f1.6 lens, hyper realistic, lifelike texture, villain, cyborg, evil, dynamic lighting, 20 years old, randy orton, Mads Mikkelsen (male) bangs,elegant, military army, cyberpunk, long messy hair, black hair jawline, chains all over his body, long black jacket, , piercings, scar in the face, light green eyes, tattoos, airbrush panting by Ed Blinkey, Atey Ghailan, hirohiko araki, Jeremy Mann, Greg Manchess, Alex Gray, (photorealistic:1.4), [:(detailed face:1.2):0.2] (detailed clothes features) (best quality:1.4),ultra high res, HDR,8k resolution , intricate, high detail, sharp focus, dramatic, octane render, manga-looking character design

cant read this one: [:(detailed face:1.2):0.2]

**Comment by uwidev** [comment]
Should be fixed with the latest commit. However, in the meantime, weighted tokens will not have their weight added to the end. That's another problem to resolve another day.
