### ISSUE TITLE
Button alignment is wrong in Vladmandic fork.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [uwidev/sd_extension-prompt_formatter#3]
I'm using the repo from https://github.com/vladmandic/automatic (a fork based on AUTOMATIC1111), but the prompt formatter icon doesn't line up properly with the rest:

![image](https://user-images.githubusercontent.com/52193044/234375555-7d528bea-055f-4f34-8c2a-6ed37794cec5.png)

**Comment by 5eu** [comment]
![image](https://user-images.githubusercontent.com/8539836/234385840-fd499de4-3473-4444-8ceb-c0a8c6839da1.png)
mine loos like this

**Comment by GalaxyTimeMachine** [comment]
This could be because of the different skins in this fork.

**Comment by uwidev** [comment]
So how the button is implemented is that we create a class that inherits from [on_before_component](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/script_callbacks.py#L321). Essentially, we look for the "paste" button, and before the UI loads the `paste` button, the UI will load the `format`. What's interesting, though, is that when I delete styles.css, my UI looks like this.

![image](https://user-images.githubusercontent.com/10101319/235062799-31f00c03-47fa-497a-a8fd-83d1c841244f.png)

Which is to say the button is not being placed within the row, but rather, outside of the row component. Even when I try to move it below `clear prompt`, it's still not placed inside of the row, actually just splitting the rows.

![image](https://user-images.githubusercontent.com/10101319/235063117-2e20d36a-b556-4ed5-b511-446e32bbae3f.png)

I'm not too familiar with gradio, so I'm not sure how to manually "inject" my UI into this row. I also just could be utilizing the provided callbacks incorrectly, or using gradio not to its full potential.

Here's where where the failed magic is (the location of the UI creation callback). If anyone could help, I'd appreciate it.
https://github.com/uwidev/sd_extension-prompt_formatter/blob/main/scripts/format_ui.py#L492

**Comment by uwidev** [comment]
[Fixed](https://github.com/uwidev/sd_extension-prompt_formatter/commit/44709fd20422e937fb746ca40f1b0e71fcc0456b)
