### ISSUE TITLE
icon doesn't show in chrome

### ISSUE THREAD

**Issue by wktra** [uwidev/sd_extension-prompt_formatter#6]
only shows a square

**Comment by uwidev** [comment]
I use Firefox. I grabbed Chrome and ran into the exact same issue. I pulled up graphmecia on Chrome and noticed a whole bunch of symbols pop up as squares, just like what you saw on your side. It seems to be a font compatibility issue (or something). I also tested on edge, and it has the same issue. As to how Firefox does it's magic, I'm currently looking into it.

The KitchenUI that did the same thing, has the same problem, though resolved it [in a round-a-bout fashion](https://github.com/canisminor1990/sd-webui-kitchen-theme/issues/68).

**Comment by uwidev** [comment]
Fixed.
