### ISSUE TITLE
Doesn't leave space after comma

### ISSUE THREAD

**Issue by theoretischer** [uwidev/sd_extension-prompt_formatter#7]
In the examples it shows a space after each comma, for me it removed it and my spell correction tool yells at my why there aren't spaces after commas. Is there a way to change it?

**Comment by theoretischer** [comment]
I changed line 127 in "format_ui.py" to `    return ', '.join(split)` and it seems to have worked for anybody wondering the same

**Comment by uwidev** [comment]
This was mentioned [here](https://github.com/uwidev/sd_extension-prompt_formatter/issues/4).

Essentially, when working on the prompt itself, it's generally easier to navigate when spaces aren't there. It's a trade of in readability for a better workflow. 

Sometime in the future, I plan on allowing you to customize how you want to automatically format your prompt, spaces included. For now, what you mentioned will work perfectly fine.

**Comment by Woisek** [comment]
>Essentially, when working on the prompt itself, it's generally easier to navigate when spaces aren't there. 

How is that "easier"? The cursor stops at the character, not at the space or comma. So basically, it doesn't matter if there are spaces after the comma or not if you STRG left/right. So I would also heavily prefer the spaces after the comma. It's not only the readability, but also the line break that matters.
Thanks for this great extension.

**Comment by theoretischer** [comment]
A lot of people like me use grammar tools because they are not native or have a disability that causes them to not be good at spelling. With these extensions and no space after a comma, it's just a giant mess, almost unusable.

**Comment by uwidev** [comment]
Resolved on commit https://github.com/uwidev/sd_extension-prompt_formatter/commit/aaa61fce2a1b0e1b7653543ef1f54669ae8ab88e.
