### ISSUE TITLE
[Issue]: AttributeError: 'ExtraNetworksPageLyCORIS' object has no attribute 'get_sort_keys'

### ISSUE THREAD

**Issue by Woisek** [uwidev/sd_extension-prompt_formatter#8]
When starting automatic, I get the following error:

python_server_full_path:  I:\Super SD 2.0\automatic\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
11:26:39-704645 INFO     Libraries loaded
11:26:40-185359 ERROR    Module load: I:\Super SD
                         2.0\automatic\extensions\sd_extension-prompt_formatter\scripts\format_ui.py: SyntaxError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Super SD 2.0\automatic\modules\script_loading.py:13 in load_module                                               │
│                                                                                                                     │
│   12 │   try:                                                                                                       │
│ > 13 │   │   module_spec.loader.exec_module(module)                                                                 │
│   14 │   except Exception as e:                                                                                     │
│ in exec_module:879                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│ in source_to_code:947                                                                                               │
│ in _call_with_frames_removed:241                                                                                    │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│  I:\Super SD 2.0\automatic\extensions\sd_extension-prompt_formatter\scripts\format_ui.py:107                        │
│ <<<<<<< Updated upstream                                                                                            │
│ ▲                                                                                                                   │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
SyntaxError: invalid syntax
11:26:40-430792 INFO     Running extension preloading
11:26:40-805781 INFO     Loading UI theme: name=black-orange style=Auto
Create LRU cache (max_size=16) for preprocessor results.
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Super SD 2.0\automatic\launch.py:149 in <module>                                                                 │
│                                                                                                                     │
│   148                                                                                                               │
│ > 149     instance = start_server(immediate=True, server=None)                                                      │
│   150     while True:                                                                                               │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\launch.py:129 in start_server                                                             │
│                                                                                                                     │
│   128         else:                                                                                                 │
│ > 129             server = server.webui()                                                                           │
│   130     if args.profile:                                                                                          │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\webui.py:276 in webui                                                                     │
│                                                                                                                     │
│   275     start_common()                                                                                            │
│ > 276     start_ui()                                                                                                │
│   277     load_model()                                                                                              │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\webui.py:204 in start_ui                                                                  │
│                                                                                                                     │
│   203     startup_timer.record("scripts before_ui_callback")                                                        │
│ > 204     shared.demo = modules.ui.create_ui()                                                                      │
│   205     startup_timer.record("ui")                                                                                │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\modules\ui.py:360 in create_ui                                                            │
│                                                                                                                     │
│    359             from modules import ui_extra_networks                                                            │
│ >  360             extra_networks_ui = ui_extra_networks.create_ui(extra_networks_ui, extra_net                     │
│    361         with gr.Row().style(equal_height=False):                                                             │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\modules\ui_extra_networks.py:214 in create_ui                                             │
│                                                                                                                     │
│   213             with gr.Tab(page.title, id=page.title.lower().replace(" ", "_")):                                 │
│ > 214                 page_elem = gr.HTML(page.create_html(ui.tabname))                                             │
│   215                 page_elem.change(fn=lambda: None, _js=f'() => refreshExtraNetworks("{tab                      │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\modules\ui_extra_networks.py:100 in create_html                                           │
│                                                                                                                     │
│    99 """ for subdir in subdirs])                                                                                   │
│ > 100         for item in self.list_items():                                                                        │
│   101             metadata = item.get("metadata")                                                                   │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\extensions-builtin\a1111-sd-webui-lycoris\ui_extra_networks_lyco.py:33 in list_items      │
│                                                                                                                     │
│   32                 "metadata": json.dumps(lyco_on_disk.metadata, indent=4) if lyco_on_disk.                       │
│ > 33                 "sort_keys": {'default': index, **self.get_sort_keys(lyco_on_disk.filena                       │
│   34             }                                                                                                  │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'ExtraNetworksPageLyCORIS' object has no attribute 'get_sort_keys'
Drücken Sie eine beliebige Taste . . .

Any ideas?
Previously, I also noted that the button was gone.

**Comment by uwidev** [comment]
What else are you using besides prompt formatted? I'm speculating that there's an extension conflict, and it might be that it might not even be related to this extension at all, since I never touched my script doesn't touch anything related to Lycoris.

Try disabling all extensions except built-in and prompt formatter. Does it still run? If so, it might be another extension playing weird with prompt formatter, or it might not be prompt formatter at all and that other extension. Give this a try and let me know how it goes.

I also noticed you're using the Photoshop. It might be that as well.

**Comment by uwidev** [comment]
Is this automatic1111's webui, vlad, or something else?

**Comment by Woisek** [comment]
It's Vlads repo.

**Comment by uwidev** [comment]
You mentioned that the prompt formatter worked before without any problem. I'm assuming it was v0.3.3? 

I will test the extension on vlad when I'm available.

**Comment by Woisek** [comment]
>You mentioned that the prompt formatter worked before without any problem. I'm assuming it was v0.3.3?

I really can't say anymore what version this was. I noticed it only, because I wanted to format a prompt, but the button was gone and I thought that Vlad had removed something again (he did an update previously).

But for your info: This is what I'm getting now:

python_server_full_path:  I:\Super SD 2.0\automatic\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
22:55:57-875419 INFO     Libraries loaded
22:55:58-413980 ERROR    Module load: I:\Super SD
                         2.0\automatic\extensions\sd_extension-prompt_formatter\scripts\format_ui.py: SyntaxError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Super SD 2.0\automatic\modules\script_loading.py:13 in load_module                                               │
│                                                                                                                     │
│   12 │   try:                                                                                                       │
│ > 13 │   │   module_spec.loader.exec_module(module)                                                                 │
│   14 │   except Exception as e:                                                                                     │
│ in exec_module:879                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│ in source_to_code:947                                                                                               │
│ in _call_with_frames_removed:241                                                                                    │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│  I:\Super SD 2.0\automatic\extensions\sd_extension-prompt_formatter\scripts\format_ui.py:107                        │
│ <<<<<<< Updated upstream                                                                                            │
│ ▲                                                                                                                   │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
SyntaxError: invalid syntax
22:55:58-677909 INFO     Running extension preloading
22:55:59-032178 INFO     Loading UI theme: name=black-orange style=Auto

Maybe this helps ...

**Comment by uwidev** [comment]
Guess what, it works on my end. 😔

I did a fresh install of vlad and the extension, it works.

Can you take a look at `I:\Super SD 2.0\automatic\extensions\sd_extension-prompt_formatter\scripts\format_ui.py`, specifically at line `107`. What do you see around there?

**Comment by Woisek** [comment]
Strange, it looks like this 😧:
![Zwischenablagebild (3)](https://github.com/uwidev/sd_extension-prompt_formatter/assets/122026301/f36609ec-2623-4db4-bf21-8979e0430c7c)

**Comment by Woisek** [comment]
OK, this seems to fixed it ... the button is here again. 🙂
I'll report if anything doesn't fit, still.
