### ISSUE TITLE
re: underscore/space toggle

### ISSUE THREAD

**Issue by fuzzyfaraway** [uwidev/sd_extension-prompt_formatter#9]
The current toggle dealing with underscores needs a tweak to disallow changing underscores to spaces when between angle brackets in a prompt. For example,  _\<lora:add_detail:1\>_ gets changed to _\<lora:add detail:1\>_ causing it to not be found when generating. The same would apply to other angle-bracketed items such as _\<hypernet:desolation\_:1\> and \<lyco:projectUnrealEngine5_v30:1.0\>_

**Comment by uwidev** [comment]
Fixed in v0.4.1
